package me.nalab.survey.web.adaptor.createsurvey;

class TestJson {

	static String json = "{\n"
		+ "  \"question_count\": 5,\n"
		+ "  \"question\": [\n"
		+ "    {\n"
		+ "      \"type\": \"choice\",\n"
		+ "      \"form_type\": \"tendency\",\n"
		+ "      \"title\": \"저는 UI, UX, GUI 중에 어떤 분야를 가장 잘하는 것 같나요?\",\n"
		+ "      \"choices\": [\n"
		+ "        {\n"
		+ "          \"content\": \"UI\",\n"
		+ "          \"order\": 1\n"
		+ "        },\n"
		+ "        {\n"
		+ "          \"content\": \"UX\",\n"
		+ "          \"order\": 2\n"
		+ "        }\n"
		+ "      ],\n"
		+ "      \"max_selectable_count\": 1,\n"
		+ "      \"order\": 1\n"
		+ "    },\n"
		+ "    {\n"
		+ "      \"type\": \"choice\",\n"
		+ "      \"form_type\": \"collaboration-experience\",\n"
		+ "      \"title\": \"저는 UI, UX, GUI 중에 어떤 분야를 가장 잘하는 것 같나요?\",\n"
		+ "      \"choices\": [\n"
		+ "        {\n"
		+ "          \"content\": \"UI\",\n"
		+ "          \"order\": 1\n"
		+ "        },\n"
		+ "        {\n"
		+ "          \"content\": \"UX\",\n"
		+ "          \"order\": 2\n"
		+ "        }\n"
		+ "      ],\n"
		+ "      \"max_selectable_count\": 1,\n"
		+ "      \"order\": 1\n"
		+ "    },\n"
		+ "    {\n"
		+ "      \"type\": \"choice\",\n"
		+ "      \"form_type\": \"position\",\n"
		+ "      \"title\": \"저는 UI, UX, GUI 중에 어떤 분야를 가장 잘하는 것 같나요?\",\n"
		+ "      \"choices\": [\n"
		+ "        {\n"
		+ "          \"content\": \"UI\",\n"
		+ "          \"order\": 1\n"
		+ "        },\n"
		+ "        {\n"
		+ "          \"content\": \"UX\",\n"
		+ "          \"order\": 2\n"
		+ "        }\n"
		+ "      ],\n"
		+ "      \"max_selectable_count\": 1,\n"
		+ "      \"order\": 1\n"
		+ "    },\n"
		+ "    {\n"
		+ "      \"type\": \"short\",\n"
		+ "      \"form_type\": \"strength\",\n"
		+ "      \"title\": \"저는 UX, UI, GUI 중에 어떤 분야에 더 강점이 있나요?\",\n"
		+ "      \"order\": 2\n"
		+ "    },\n"
		+ "    {\n"
		+ "      \"type\": \"short\",\n"
		+ "      \"form_type\": \"weakness\",\n"
		+ "      \"title\": \"저는 UX, UI, GUI 중에 어떤 분야에 더 강점이 있나요?\",\n"
		+ "      \"order\": 2\n"
		+ "    },\n"
		+ "    {\n"
		+ "      \"type\": \"short\",\n"
		+ "      \"form_type\": \"custom\",\n"
		+ "      \"title\": \"저는 UX, UI, GUI 중에 어떤 분야에 더 강점이 있나요?\",\n"
		+ "      \"order\": 2\n"
		+ "    }\n"
		+ "  ]\n"
		+ "}";

}
